version: "3.9"
services:
  db:
    container_name: "db"
    image: "postgres:13"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  cache:
    driver: local
  database-data:
