/todo/{id}:
  get:
    tags:
      - developers
    summary: searches inventory
    description: |
      By passing in the appropriate options, you can search for
      available inventory in the system
    operationId: getTodo
    parameters:
      - name: id
        in: path
        description: pass an optional search string for looking up inventory
        required: true
        schema:
          type: string
    responses:
      "200":
        description: search results matching criteria
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      "400":
        description: bad input parameter

  put:
    tags:
      - admins
    summary: adds an inventory item
    description: Adds an item to the system
    operationId: updateTodo
    parameters:
      - name: id
        in: path
        description: pass an optional search string for looking up inventory
        required: true
        schema:
          type: string
    requestBody:
      description: Inventory item to add
      content:
        application/json:
          schema:
            type: 'object'
            properties:
              title:
                type: string
              description:
                type: string
    responses:
      "200":
        description: search results matching criteria
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      "400":
        description: "invalid input, object invalid"
      "409":
        description: an existing item already exists

  delete:
    tags:
      - admins
    summary: deletes an inventory item
    description: Deletes an item from the system
    operationId: deleteTodo
    parameters:
      - name: id
        in: path
        description: pass an optional search string for looking up inventory
        required: true
        schema:
          type: string
    responses:
      "204":
        description: search results matching criteria
      "400":
        description: "invalid input, object invalid"

/todo:
  get:
    tags:
      - admins
    summary: searches inventory
    description: |
      By passing in the appropriate options, you can search for
      available inventory in the system
    operationId: listTodo
    responses:
      "200":
        description: search results matching criteria
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Todo'
      "400":
        description: bad input parameter
  post:
    tags:
      - admins
    summary: adds an inventory item
    description: Adds an item to the system
    operationId: addTodo
    requestBody:
      description: Inventory item to add
      content:
        application/json:
          schema:
            type: 'object'
            required:
              - title
              - description
            properties:
              title:
                type: string
              description:
                type: string
    responses:
      "201":
        description: item created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        headers:
          Location:
            description: The URL of the created item
            schema:
              type: string
      "400":
        description: "invalid input, object invalid"
      "409":
        description: an existing item already exists
